
services:
  postgres:
    image: postgres:latest
    container_name: Store_Container
    environment:
      - POSTGRES_DB=StoreDB
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:

